import assert from 'node:assert/strict';
import { createLightPool } from '../js/lightpool.js';
const a={position:{x:0,y:0,z:0},intensity:20,distance:10};
const b={position:{x:20,y:0,z:0},intensity:20,distance:10};
const pool=createLightPool(1);
pool.select([a,b],a.position);
assert.equal(pool.slots[0].source,a);assert.equal(pool.slots[0].weight,1);
pool.select([a,b],b.position);
pool.advance(.05);
assert.equal(pool.slots[0].source,a,'source cannot teleport before fading out');
assert(pool.slots[0].weight>0 && pool.slots[0].weight<1);
for(let i=0;i<12;i++)pool.advance(.05);
assert.equal(pool.slots[0].source,b);assert.equal(pool.slots[0].weight,1,'fade completes even when the player stops');
pool.select([],a.position);
for(let i=0;i<5;i++)pool.advance(.05);
assert.equal(pool.slots[0].source,null);assert.equal(pool.slots[0].weight,0);
const stable=createLightPool(1);
stable.select([a,b],{x:9.9,y:0,z:0});stable.select([a,b],{x:10.1,y:0,z:0});
assert.equal(stable.slots[0].target,a,'hysteresis avoids flicker near an equal-distance boundary');
const two=createLightPool(2);two.select([a,b],a.position);two.select([b,a],b.position);
assert.equal(two.slots[0].source,a,'still-selected fixtures retain their renderer slots');
assert.equal(two.slots[1].source,b);
console.log('LIGHT POOL TESTS PASSED: startup, fade-out/in, stationary completion, empty selection, hysteresis, stable slots');
