import assert from 'node:assert/strict';
import { buildLayout } from '../js/config.js';
import { createPlayer } from '../js/player.js';
const window = globalThis.window = new EventTarget();
window.matchMedia = () => ({ matches: false });
const document = globalThis.document = new EventTarget();
const canvas = new EventTarget();
const fire = (target, type, props = {}) => target.dispatchEvent(Object.assign(new Event(type), props));
canvas.requestPointerLock = () => { document.pointerLockElement = canvas; fire(document, 'pointerlockchange'); };
document.exitPointerLock = () => { document.pointerLockElement = null; fire(document, 'pointerlockchange'); };
const camera = { rotation: {}, position: { set(x, y, z) { Object.assign(this, { x, y, z }); } } };
let steps = 0, errors = 0;
const layout = buildLayout();
const player = createPlayer({ camera, domElement: canvas, layout, initialState: { x: 3, y: 0, z: 0, theta: 0, yaw: -Math.PI / 2 }, onFootstep: () => steps++, onLockError: () => errors++ });
player.requestLock();
fire(window, 'keydown', { code: 'KeyW', repeat: false });
player.update(0.05);
assert(player.getState().x > 3, 'forward input moves on the landing');
document.exitPointerLock();
const paused = { ...player.getState() };
player.update(0.05);
assert.deepEqual(player.getState(), paused);
player.requestLock();
player.update(0.05);
assert.deepEqual(player.getState(), paused, 'resume clears a key held before pausing');
fire(window, 'keydown', { code: 'KeyW', repeat: false });
player.setSuspended(true);
player.update(0.05);
assert.deepEqual(player.getState(), paused, 'reading a record freezes movement');
player.setSuspended(false);
player.update(0.05);
assert.deepEqual(player.getState(), paused, 'closing a record does not resume stale input');
fire(window, 'keydown', { code: 'KeyW', repeat: false });
fire(window, 'blur');
player.update(0.05);
assert.deepEqual(player.getState(), paused, 'switching windows clears movement');
Object.assign(player.getState(), { x: 22.65, z: 0, theta: layout.stations[1].theta, level: 1, y: layout.stations[1].y });
fire(window, 'keydown', { code: 'KeyW', repeat: false });
steps = 0;
for (let i = 0; i < 80; i++) player.update(0.05);
assert.equal(steps, 0, 'a blocked walker does not make footsteps');
document.exitPointerLock();
canvas.requestPointerLock = () => Promise.reject(new Error('blocked'));
player.requestLock();
await new Promise(resolve => setTimeout(resolve, 0));
assert.equal(errors, 1, 'pointer lock failures have a retry path');
console.log('PLAYER TESTS PASSED: input, pause, resume, reading, focus loss, footsteps, pointer-lock error');
