import assert from 'node:assert/strict';
import { createProgress, createSaveStore, SAVE_KEY } from '../js/progress.js';
import { buildLayout } from '../js/config.js';
const layout=buildLayout(),data=new Map(),storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)};
const store=createSaveStore(()=>storage,layout,'test');
const p={x:3,y:0,z:0,theta:0,level:null,yaw:1.2,pitch:-.4};
const progress=createProgress();
assert.equal(progress.complete('screen'),true);
assert.equal(progress.complete('screen'),false);
assert.equal(progress.read('topo'),true);
progress.complete('gallery');
assert.equal(progress.snapshot().completed.length,3);
assert(store.save(p,progress.snapshot()).save);
assert.deepEqual(store.load().save.player,p);
assert.deepEqual(createProgress(store.load().save.progress).snapshot(),progress.snapshot());
progress.door('apt-28-a',true);
assert(store.save(p,progress.snapshot()).save);
assert.equal(store.load().save.progress.doors['apt-28-a'],true);
assert(store.save(p,{...progress.snapshot(),doors:{invalid:true}}).error);
assert(store.save({...p,theta:-.2},progress.snapshot()).save,'top landing accepts negative bearing');
const valid=data.get(SAVE_KEY);
assert(store.save({...p,x:Infinity},progress.snapshot()).error);
assert.equal(data.get(SAVE_KEY),valid,'invalid write preserves previous save');
assert(createSaveStore(()=>storage,layout,'different').load().error);
assert.equal(data.get(SAVE_KEY),valid);
data.set(SAVE_KEY,'{bad');assert(store.load().error);assert.equal(data.get(SAVE_KEY),'{bad');
assert(createSaveStore(()=>{throw Error('denied')},layout,'test').load().error);
assert(createSaveStore(()=>({setItem(){throw Error('full')}}),layout,'test').save(p,progress.snapshot()).error);
console.log('PROGRESS TESTS PASSED: roundtrip, orientation, out-of-order objectives, corrupt/incompatible saves, denied storage, quota failure');
